FROM node:16.18.1
RUN apt-get update

WORKDIR /app
COPY . ./

EXPOSE 3002

# Default powerline10k theme, no plugins installed
RUN sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v1.1.3/zsh-in-docker.sh)"

RUN npm run install-dev