# fly.toml app configuration file generated for full-stack-boilerplate on 2023-11-13T18:20:18+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "full-stack-boilerplate"
primary_region = "cdg"

[build]

[deploy]
  release_command = "npm run release-command"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
